#!/usr/bin/env python3
"""
Synchronize .claude/schedules.json to system scheduler (cron or systemd).

Usage:
    sync-schedules.py [--project-dir PATH] [--dry-run]

Safety:
    - Only modifies CLAUDE-MANAGED section of crontab
    - Creates backup before modification
    - Validates all entries before applying
"""

import argparse
import hashlib
import json
import re
import shlex
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Constants
CRONTAB_MARKER = "# CLAUDE-MANAGED-TASKS"
CRONTAB_END = "# END-CLAUDE-MANAGED-TASKS"
SYSTEMD_USER_DIR = Path.home() / ".config/systemd/user"
BACKUP_DIR = Path.home() / ".claude/backups"

# Task ids are used in filenames, systemd unit names, and crontab comments, so
# they must be a conservative slug — no path separators, shell metacharacters,
# or whitespace. Validated before any task is materialized.
TASK_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")

# Named-month aliases for the cron month field (case-insensitive).
_MONTH_NAMES = {
    "jan": "01", "feb": "02", "mar": "03", "apr": "04",
    "may": "05", "jun": "06", "jul": "07", "aug": "08",
    "sep": "09", "oct": "10", "nov": "11", "dec": "12",
}


def valid_task_id(task_id: str) -> bool:
    """True if task_id is a safe slug for filenames and unit names."""
    return bool(task_id) and bool(TASK_ID_RE.match(task_id)) and len(task_id) <= 128


def project_hash(project_dir: Path) -> str:
    """Stable short hash of a project path.

    Uses hashlib (not the builtin hash(), which is salted per-process) so the
    systemd cleanup glob matches units created by previous runs — otherwise
    every sync orphans the prior run's timers instead of replacing them.
    """
    return hashlib.sha1(str(project_dir).encode("utf-8")).hexdigest()[:8]


def sanitize_line(text: str) -> str:
    """Collapse newlines/CRs so user text can't inject extra unit directives
    or crontab lines when interpolated into a unit Description or comment."""
    return " ".join(str(text).split())


def resolve_timeout_bin() -> Optional[str]:
    """Path to a coreutils-style timeout binary, or None.

    `timeout` on Linux; `gtimeout` on macOS (Homebrew coreutils). When absent,
    inline cron tasks run without a hard wall-clock cap (systemd tasks still
    get TimeoutStartSec from the unit)."""
    return shutil.which("timeout") or shutil.which("gtimeout")


def write_task_runner(task: dict, project_dir: Path, runner_dir: Path,
                      timeout_bin: Optional[str], dry_run: bool = False) -> Path:
    """Write an executable per-task runner script and return its path.

    Every task-controlled value (command, allowed tools, working directory) is
    embedded here as a properly shell-quoted token, so neither the systemd unit
    nor the crontab line ever interpolates untrusted task content into a shell
    context. This is what removes the command-injection surface: the unit/cron
    entry references only this script's controlled path.
    """
    task_id = task["id"]
    tools = ",".join(task.get("permissions", {}).get("allowedTools",
                                                     ["Read", "Grep", "Glob"]))
    timeout = int(task.get("timeout", 300))
    work_dir = task.get("workingDirectory", str(project_dir))
    log_file = project_dir / f".claude/logs/{task_id}.log"
    runner = runner_dir / f"{task_id}.sh"

    timeout_prefix = f"{shlex.quote(timeout_bin)} {timeout} " if timeout_bin else ""
    script = (
        "#!/bin/bash\n"
        f"# Auto-generated by sync-schedules.py for task: {task_id}\n"
        "# Regenerated on every `schedule sync` — do not edit by hand.\n"
        "set -euo pipefail\n"
        f"cd {shlex.quote(str(work_dir))}\n"
        f"exec {timeout_prefix}claude -p {shlex.quote(task['command'])} "
        f"--allowedTools {shlex.quote(tools)} "
        f">> {shlex.quote(str(log_file))} 2>&1\n"
    )

    if not dry_run:
        runner_dir.mkdir(parents=True, exist_ok=True)
        log_file.parent.mkdir(parents=True, exist_ok=True)
        runner.write_text(script)
        runner.chmod(0o700)
    return runner


def prune_task_runners(runner_dir: Path, keep_ids: set) -> None:
    """Remove runner scripts for tasks no longer present/enabled."""
    if not runner_dir.is_dir():
        return
    for f in runner_dir.glob("*.sh"):
        if f.stem not in keep_ids:
            f.unlink()


def detect_scheduler() -> str:
    """Detect available scheduler: systemd or cron."""
    # Check for systemd user session
    try:
        result = subprocess.run(
            ["systemctl", "--user", "status"],
            capture_output=True,
            timeout=5
        )
        if result.returncode in (0, 3):  # 0=running, 3=no units active
            return "systemd"
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    # Check for cron
    try:
        subprocess.run(["crontab", "-l"], capture_output=True, timeout=5)
        return "cron"
    except (subprocess.TimeoutExpired, FileNotFoundError):
        pass

    return "none"


# Named tokens accepted in the month (field 3) and day-of-week (field 4)
# positions -- kept in lockstep with cron_to_oncalendar, which converts named
# months to 01..12 and named weekdays to systemd's three-letter names. If a name
# parses here but not there (or vice versa) a task is silently dropped, so the
# two MUST agree.
_MONTH_TOKENS = set(_MONTH_NAMES)  # jan..dec
_DOW_TOKENS = {"sun", "mon", "tue", "wed", "thu", "fri", "sat"}


def validate_cron_expression(expr: str) -> bool:
    """Validate cron expression syntax (5 fields).

    Fields are minute, hour, day-of-month, month, day-of-week. The month and
    day-of-week fields additionally accept their named forms (jan..dec /
    sun..sat, case-insensitive) so this gate does not reject expressions that
    cron_to_oncalendar can in fact convert.
    """
    parts = expr.split()
    if len(parts) != 5:
        return False

    # Per-field set of accepted names (empty = digits only).
    field_names = ({}, {}, {}, _MONTH_TOKENS, _DOW_TOKENS)

    def token_ok(token: str, names) -> bool:
        return token.isdigit() or token.lower() in names

    for i, part in enumerate(parts):
        names = field_names[i]
        # Handle wildcards
        if part == "*":
            continue
        # Handle step values: BASE/N (N must be a positive integer)
        if "/" in part:
            base, step = part.split("/", 1)
            if not step.isdigit():
                return False
            part = base
            if part == "*":
                continue
        # Handle ranges
        if "-" in part:
            try:
                start, end = part.split("-", 1)
                if not (token_ok(start, names) and token_ok(end, names)):
                    return False
            except ValueError:
                return False
            continue
        # Handle lists
        for segment in part.split(","):
            if segment != "*" and not token_ok(segment, names):
                return False

    return True


def load_schedules(project_dir: Path) -> dict:
    """Load schedules.json from project."""
    schedules_file = project_dir / ".claude/schedules.json"
    if not schedules_file.exists():
        return {"version": "1.0", "tasks": []}

    with open(schedules_file) as f:
        return json.load(f)


def backup_crontab() -> Optional[Path]:
    """Backup current crontab before modification."""
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    backup_file = BACKUP_DIR / f"crontab-{datetime.now():%Y%m%d-%H%M%S}.bak"

    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        if result.returncode == 0:
            backup_file.write_text(result.stdout)
            return backup_file
    except Exception:
        pass

    return None


def sync_to_cron(tasks: list, project_dir: Path, dry_run: bool = False) -> dict:
    """Sync tasks to user crontab."""
    # Backup first
    backup_path = None
    if not dry_run:
        backup_path = backup_crontab()

    # Read existing crontab
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing_lines = result.stdout.splitlines() if result.returncode == 0 else []

    # Remove existing CLAUDE-MANAGED section
    new_lines = []
    in_managed_section = False
    for line in existing_lines:
        if line.strip() == CRONTAB_MARKER:
            in_managed_section = True
            continue
        if line.strip() == CRONTAB_END:
            in_managed_section = False
            continue
        if not in_managed_section:
            new_lines.append(line)

    # Filter to enabled tasks only
    enabled_tasks = [t for t in tasks if t.get("enabled", True)]

    # Reconcile runner scripts unconditionally: an empty enabled set means prune
    # ALL of this project's runners (emptying schedules.json must strand nothing,
    # mirroring the systemd path). The CLAUDE-MANAGED crontab section was already
    # stripped above, so when enabled_tasks is empty we simply never re-add it.
    runner_dir = project_dir / ".claude" / "schedules.d"
    if not dry_run:
        prune_task_runners(runner_dir, {t["id"] for t in enabled_tasks})

    # Add new CLAUDE-MANAGED section
    if enabled_tasks:
        new_lines.append("")
        new_lines.append(CRONTAB_MARKER)
        new_lines.append(f"# Generated: {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}")
        new_lines.append(f"# Project: {project_dir}")
        new_lines.append(f"# Tasks: {len(enabled_tasks)}")

        # Each task runs via its own generated runner script (see
        # write_task_runner): the crontab line references only that controlled
        # path, never the task's command/tools, so there is no shell-injection
        # surface in the crontab itself.
        timeout_bin = resolve_timeout_bin()
        if timeout_bin is None:
            print("Warning: no `timeout`/`gtimeout` on PATH; cron tasks will run "
                  "without a hard time limit (on macOS: brew install coreutils).",
                  file=sys.stderr)

        for task in enabled_tasks:
            runner = write_task_runner(task, project_dir, runner_dir,
                                       timeout_bin, dry_run=dry_run)
            label = sanitize_line(task.get("name", "Unnamed"))
            new_lines.append(f"# Task: {task['id']} - {label}")
            new_lines.append(f"{task['schedule']} {shlex.quote(str(runner))}")

        new_lines.append(CRONTAB_END)

    new_crontab = "\n".join(new_lines) + "\n"

    if dry_run:
        return {
            "success": True,
            "method": "cron",
            "dry_run": True,
            "content": new_crontab,
            "task_count": len(enabled_tasks)
        }

    # Apply new crontab
    proc = subprocess.run(
        ["crontab", "-"],
        input=new_crontab,
        text=True,
        capture_output=True
    )

    if proc.returncode != 0:
        return {
            "success": False,
            "method": "cron",
            "error": proc.stderr
        }

    return {
        "success": True,
        "method": "cron",
        "task_count": len(enabled_tasks),
        "backup": str(backup_path) if backup_path else None
    }


def _convert_calendar_member(member: str, *, names: dict | None = None,
                             pad: bool = True, step_base: str = "0") -> str:
    """Convert a single member of a cron numeric/date field to systemd syntax.

    Handles the member forms that may appear inside a comma list:
      *        -> *
      a        -> 0a   (zero-padded to two digits when pad and numeric)
      a-b      -> a..b (systemd numeric ranges use '..', never '-')
      */n      -> <step_base>/n  (repetition base must be a number, not '*')
      a-b/n    -> a..b/n
    `step_base` is the value a bare '*/n' rebases on: '0' for the time fields
    (hour/minute, whose floor is 0) and '1' for the date fields (month and
    day-of-month, whose floor is 1 - systemd rejects '0/n' there with "Invalid
    argument"). `names` (e.g. month aliases) maps lowercased tokens to their
    numeric form; applied to plain values and range endpoints. Day-of-week is
    handled separately (it keeps three-letter systemd names), so this is used
    for minute, hour, day-of-month and month.
    """
    names = names or {}

    def value(token: str) -> str:
        low = token.lower()
        if low in names:
            return names[low]
        if pad and token.isdigit():
            return token.zfill(2)
        return token

    # Step: BASE/N  (BASE may itself be '*' or a range)
    if "/" in member:
        base, step = member.split("/", 1)
        if base == "*":
            base_out = step_base
        else:
            base_out = _convert_calendar_member(
                base, names=names, pad=pad, step_base=step_base)
        return f"{base_out}/{step}"
    # Range: A-B  -> A..B
    if "-" in member:
        start, end = member.split("-", 1)
        return f"{value(start)}..{value(end)}"
    # Bare wildcard or single value
    if member == "*":
        return "*"
    return value(member)


def _convert_calendar_field(field: str, *, names: dict | None = None,
                            pad: bool = True, step_base: str = "0") -> str:
    """Convert a whole cron field (possibly a comma list of members)."""
    if field == "*":
        return "*"
    return ",".join(
        _convert_calendar_member(m, names=names, pad=pad, step_base=step_base)
        for m in field.split(",")
    )


def cron_to_oncalendar(cron_expr: str) -> str:
    """Convert a 5-field cron expression to a systemd OnCalendar expression.

    All five cron fields are converted with a single robust member-converter:
    step '*/N' becomes '0/N' (systemd's repetition base must be numeric), ranges
    'A-B' become 'A..B' (systemd numeric fields reject '-'), range-steps
    'A-B/N' become 'A..B/N', single time values are zero-padded, and named
    months (jan..dec) become 01..12. Day-of-week keeps systemd's three-letter
    names. The result is assembled as

        <DOW> <YEAR>-<MONTH>-<DOM> <HH>:<MM>:00

    (the DOW prefix is omitted when the cron dow field is '*'). The expression is
    meant to be validated with `systemd-analyze calendar` before a unit is
    written (see oncalendar_for_task), which raises rather than emit a bad spec.
    """
    parts = cron_expr.split()
    if len(parts) != 5:
        return "*-*-* *:*:00"

    minute, hour, dom, month, dow = parts

    # Keep the @-shortcut keywords systemd understands for the exact patterns.
    if cron_expr == "0 * * * *":
        return "hourly"
    if cron_expr == "0 0 * * *":
        return "daily"
    if cron_expr == "0 0 * * 0":
        return "weekly"
    if cron_expr == "0 0 1 * *":
        return "monthly"

    # Day of week -> systemd's three-letter names (its own name handling).
    dow_map = {"0": "Sun", "1": "Mon", "2": "Tue", "3": "Wed",
               "4": "Thu", "5": "Fri", "6": "Sat", "7": "Sun"}

    result_dow = ""
    if dow != "*":
        if "-" in dow:
            start, end = dow.split("-", 1)
            result_dow = f"{dow_map.get(start, start)}..{dow_map.get(end, end)} "
        else:
            members = ",".join(dow_map.get(d, d) for d in dow.split(","))
            result_dow = f"{members} "

    # Date fields: month accepts named aliases; values are not zero-padded but
    # ranges/steps still need '..'/step rewriting. Date '*/N' rebases on 1 (the
    # field floor) -- systemd rejects '0/N' in month/day-of-month.
    out_month = _convert_calendar_field(month, names=_MONTH_NAMES, pad=False,
                                        step_base="1")
    out_dom = _convert_calendar_field(dom, pad=False, step_base="1")
    result_date = f"*-{out_month}-{out_dom}"

    # Time fields: zero-pad single values to two digits.
    out_min = _convert_calendar_field(minute, pad=True)
    out_hour = _convert_calendar_field(hour, pad=True)
    result_time = f"{out_hour}:{out_min}:00"

    return f"{result_dow}{result_date} {result_time}".strip()


def validate_oncalendar(expr: str) -> bool:
    """True if systemd accepts this OnCalendar expression.

    Runs `systemd-analyze calendar`; returncode 0 means the spec parses. If
    systemd-analyze is unavailable, fall back to True (best-effort) so the sync
    still works on systems without it — sync_to_systemd's verify step provides a
    second line of defense there.
    """
    try:
        result = subprocess.run(
            ["systemd-analyze", "calendar", expr],
            capture_output=True, timeout=5,
        )
        return result.returncode == 0
    except FileNotFoundError:
        return True
    except subprocess.TimeoutExpired:
        return False


def oncalendar_for_task(cron_expr: str) -> str:
    """Build and validate an OnCalendar expression, or raise ValueError.

    Raising (rather than writing a unit with a bad spec) is what keeps a broken
    schedule out of systemd: the caller records the error for that task instead
    of enabling a timer that systemd would reject.
    """
    expr = cron_to_oncalendar(cron_expr)
    if not validate_oncalendar(expr):
        raise ValueError(
            f"cron {cron_expr!r} produced OnCalendar {expr!r} that "
            "systemd-analyze rejected"
        )
    return expr


def _wants_symlink(timer_name: str) -> Path:
    """Path to the timers.target.wants symlink systemd creates on `enable`."""
    return SYSTEMD_USER_DIR / "timers.target.wants" / timer_name


def remove_systemd_unit(unit_name: str) -> None:
    """Fully remove a claude-task unit pair: disable, delete both unit files,
    and delete the timers.target.wants/<unit>.timer symlink.

    `systemctl --user disable` is supposed to drop the wants-symlink, but it is a
    no-op if the unit file is already gone or the daemon hasn't reloaded — that
    is exactly how an orphan timer got stranded after schedules.json was emptied.
    Deleting the symlink unconditionally closes that gap. Caller is responsible
    for the daemon-reload afterwards.
    """
    service_file = SYSTEMD_USER_DIR / f"{unit_name}.service"
    timer_file = SYSTEMD_USER_DIR / f"{unit_name}.timer"
    timer_name = f"{unit_name}.timer"

    # Best-effort stop + disable (ignore failures: unit may be unknown already)
    subprocess.run(["systemctl", "--user", "stop", timer_name],
                   capture_output=True)
    subprocess.run(["systemctl", "--user", "disable", timer_name],
                   capture_output=True)

    # Delete the unit files and the enable symlink, whatever disable did
    for p in (timer_file, service_file, _wants_symlink(timer_name)):
        try:
            p.unlink()
        except FileNotFoundError:
            pass


def sync_to_systemd(tasks: list, project_dir: Path, dry_run: bool = False) -> dict:
    """Sync tasks to systemd user timers."""
    SYSTEMD_USER_DIR.mkdir(parents=True, exist_ok=True)

    # Track what we create
    created = []
    errors = []

    # Filter to enabled tasks
    enabled_tasks = [t for t in tasks if t.get("enabled", True)]

    # Reconcile: remove every previously-synced unit for this project that is no
    # longer in the enabled set. Glob BOTH .service and .timer so an orphan timer
    # whose .service was already removed is still caught, and run this even when
    # enabled_tasks is empty (emptying schedules.json must strand nothing).
    phash = project_hash(project_dir)
    keep_units = {f"claude-task-{phash}-{t['id']}" for t in enabled_tasks}
    stale_units = set()
    for pattern in (f"claude-task-{phash}-*.service", f"claude-task-{phash}-*.timer"):
        for f in SYSTEMD_USER_DIR.glob(pattern):
            unit_name = f.stem  # filename minus its .service/.timer suffix
            if unit_name not in keep_units:
                stale_units.add(unit_name)
    if stale_units and not dry_run:
        for unit_name in stale_units:
            remove_systemd_unit(unit_name)
        # daemon-reload so systemd forgets the units we just deleted
        subprocess.run(["systemctl", "--user", "daemon-reload"],
                       capture_output=True)

    runner_dir = project_dir / ".claude" / "schedules.d"
    timeout_bin = resolve_timeout_bin()
    prune_task_runners(runner_dir, {t["id"] for t in enabled_tasks})

    for task in enabled_tasks:
        task_id = task["id"]
        unit_name = f"claude-task-{phash}-{task_id}"
        timeout = int(task.get("timeout", 300))
        desc = sanitize_line(task.get("name", task_id))

        # The task's command and allowed tools live only inside this runner
        # script (see write_task_runner), never in the unit text — so the unit
        # cannot be a shell-injection vector. systemd just execs the script.
        runner = write_task_runner(task, project_dir, runner_dir,
                                   timeout_bin, dry_run=dry_run)

        # Generate service file
        service_content = f"""[Unit]
Description=Claude Task: {desc}
Documentation=file://{project_dir}/.claude/schedules.json

[Service]
Type=oneshot
ExecStart={shlex.quote(str(runner))}
TimeoutStartSec={timeout}
"""

        # Build + validate the OnCalendar expression. A bad spec raises here, so
        # we record an error for the task instead of writing a unit systemd will
        # reject ("Timer unit lacks value setting. Refusing.").
        try:
            on_calendar = oncalendar_for_task(task["schedule"])
        except ValueError as e:
            errors.append({"task_id": task_id, "error": str(e)})
            continue

        timer_content = f"""[Unit]
Description=Timer for Claude Task: {desc}

[Timer]
OnCalendar={on_calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""

        service_file = SYSTEMD_USER_DIR / f"{unit_name}.service"
        timer_file = SYSTEMD_USER_DIR / f"{unit_name}.timer"

        if dry_run:
            created.append({
                "task_id": task_id,
                "service": str(service_file),
                "timer": str(timer_file),
                "on_calendar": on_calendar
            })
            continue

        try:
            # Write unit files (write_task_runner already created the log dir)
            service_file.write_text(service_content)
            timer_file.write_text(timer_content)

            subprocess.run(["systemctl", "--user", "daemon-reload"],
                         capture_output=True, check=True)

            # Verify the written unit before enabling. `systemd-analyze verify`
            # surfaces a bad setting on stderr even when it exits 0, so treat any
            # stderr mentioning this unit (or a non-zero exit) as a failure and
            # roll back rather than enable a broken timer.
            verify = subprocess.run(
                ["systemd-analyze", "--user", "verify", timer_file.name],
                capture_output=True, text=True,
            )
            verify_msg = (verify.stderr or "").strip()
            bad = verify.returncode != 0 or (
                verify_msg and unit_name in verify_msg
            )
            if bad:
                remove_systemd_unit(unit_name)
                subprocess.run(["systemctl", "--user", "daemon-reload"],
                               capture_output=True)
                errors.append({
                    "task_id": task_id,
                    "error": f"systemd-analyze verify rejected unit: "
                             f"{verify_msg or f'exit {verify.returncode}'}",
                })
                continue

            subprocess.run(["systemctl", "--user", "enable", timer_file.name],
                         capture_output=True, check=True)
            subprocess.run(["systemctl", "--user", "start", timer_file.name],
                         capture_output=True, check=True)

            created.append(task_id)
        except Exception as e:
            # Roll back any half-written unit so a failure never leaves a partial
            # service/timer pair behind.
            remove_systemd_unit(unit_name)
            subprocess.run(["systemctl", "--user", "daemon-reload"],
                           capture_output=True)
            errors.append({"task_id": task_id, "error": str(e)})

    return {
        "success": len(errors) == 0,
        "method": "systemd",
        "dry_run": dry_run,
        "task_count": len(created),
        "tasks": created,
        "errors": errors if errors else None
    }


def main():
    parser = argparse.ArgumentParser(
        description="Sync Claude schedules to system scheduler"
    )
    parser.add_argument(
        "--project-dir",
        type=Path,
        default=Path.cwd(),
        help="Project directory containing .claude/schedules.json"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes"
    )
    parser.add_argument(
        "--force-cron",
        action="store_true",
        help="Force use of cron even if systemd is available"
    )
    args = parser.parse_args()

    # Resolve project directory
    project_dir = args.project_dir.resolve()

    # Load schedules
    schedules = load_schedules(project_dir)
    tasks = schedules.get("tasks", [])

    # Validate tasks. Invalid entries are dropped (with a warning), not fatal:
    # the surviving set may legitimately be empty.
    valid_tasks = []
    for task in tasks:
        task_id = task.get("id", "")
        if not valid_task_id(task_id):
            print(f"Warning: Skipping task with invalid id {task_id!r} "
                  f"(allowed: letters, digits, dot, dash, underscore)",
                  file=sys.stderr)
            continue
        if "command" not in task or not str(task.get("command", "")).strip():
            print(f"Warning: Skipping task {task_id!r}: missing 'command'",
                  file=sys.stderr)
            continue
        schedule = task.get("schedule", "")
        if not validate_cron_expression(schedule):
            print(f"Warning: Invalid cron expression for task {task_id}: {schedule}",
                  file=sys.stderr)
            continue
        valid_tasks.append(task)

    # IMPORTANT: do NOT short-circuit when valid_tasks is empty. An empty set is
    # the signal to reconcile DOWN to nothing -- emptying schedules.json (or
    # invalidating every task) must still drive the scheduler's prune path so a
    # previously-synced unit/crontab entry is removed, not stranded. The sync
    # functions treat an empty enabled list as "remove everything for this
    # project" (systemd: glob+remove stale units, daemon-reload; cron: drop the
    # CLAUDE-MANAGED section).
    scheduler = "cron" if args.force_cron else detect_scheduler()

    if scheduler == "systemd":
        result = sync_to_systemd(valid_tasks, project_dir, args.dry_run)
    elif scheduler == "cron":
        result = sync_to_cron(valid_tasks, project_dir, args.dry_run)
    else:
        result = {
            "success": False,
            "error": "No scheduler available. Install cron or enable systemd user session."
        }

    if not valid_tasks and result.get("success"):
        result.setdefault(
            "message",
            "No active tasks; reconciled scheduler down to zero for this project.",
        )

    print(json.dumps(result, indent=2, default=str))
    sys.exit(0 if result.get("success") else 1)


if __name__ == "__main__":
    main()
