#!/usr/bin/env bash
# identity-merge.sh — concatenate the asha identity layer into a single file.
#
# Sources (in concatenation order):
#   1. <asha>/identity/asha-identity-system-prompt.md  (priority assertion)
#   2. ~/.asha/soul.md                                 (who Asha is)
#   3. ~/.asha/voice.md                                (expression style)
#   4. ~/.asha/keeper.md                               (user calibration)
#
# Output: a single markdown file usable as Codex's `model_instructions_file`.
# The generated hot layer is capped at 24 KiB by default. Extended identity
# history and writing-voice specimens remain on-demand references and are not
# concatenated here.
#
# Idempotent: only rewrites the destination if content differs (preserves mtime
# for drift-check freshness comparison).
#
# Usage:
#   identity-merge.sh <output-path>
#
# Exits 0 on success or no-op, 1 when any hot identity source is missing or the
# merged output exceeds its budget.

set -euo pipefail

# Resolve this script's dir, following symlinks. Portable (no GNU `readlink -f`).
# asha-bootstrap-symlink-walk: resolve our own real path, portable (readlink -f is GNU-only).
# Duplicated across 6 scripts — find all: `grep -rn asha-bootstrap-symlink-walk`. Cannot DRY into
# lib/portable.sh:resolve_path() — this runs *before* portable.sh is locatable. Keep copies in sync.
__asha_src="${BASH_SOURCE[0]}"
while [ -h "$__asha_src" ]; do
  __asha_dir="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
  __asha_src="$(readlink "$__asha_src")"
  case "$__asha_src" in /*) ;; *) __asha_src="$__asha_dir/$__asha_src" ;; esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
unset __asha_src __asha_dir
IDENTITY_FILE="$SCRIPT_DIR/asha-identity-system-prompt.md"

OUTPUT="${1:-}"
[[ -n "$OUTPUT" ]] || { echo "usage: $0 <output-path>" >&2; exit 1; }

[[ -f "$IDENTITY_FILE" ]] || { echo "ERROR: identity file missing: $IDENTITY_FILE" >&2; exit 1; }

USER_ASHA="${ASHA_HOME:-$HOME/.asha}"
MAX_BYTES="${ASHA_IDENTITY_MAX_BYTES:-24576}"
[[ "$MAX_BYTES" =~ ^[0-9]+$ && "$MAX_BYTES" -ge 4096 ]] \
  || { echo "ERROR: ASHA_IDENTITY_MAX_BYTES must be an integer >= 4096" >&2; exit 1; }
SOURCES=(
  "$IDENTITY_FILE"
  "$USER_ASHA/soul.md"
  "$USER_ASHA/voice.md"
  "$USER_ASHA/keeper.md"
)
for src in "${SOURCES[@]}"; do
  [[ -f "$src" ]] || { echo "ERROR: identity source missing: $src" >&2; exit 1; }
done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Asha Identity Layer (merged)"
  echo ""
  echo "_This file is generated by \`identity-merge.sh\`. Edits will be overwritten."
  echo "Source of truth: \`$IDENTITY_FILE\` and \`~/.asha/{soul,voice,keeper}.md\`._"
  echo ""

  for src in "${SOURCES[@]}"; do
    echo ""
    echo "<!-- ---- merged from: $src ---- -->"
    echo ""
    cat "$src"
    echo ""
  done
} > "$tmp"

merged_bytes="$(wc -c < "$tmp" | tr -d '[:space:]')"
if (( merged_bytes > MAX_BYTES )); then
  echo "ERROR: merged identity is $merged_bytes bytes; limit is $MAX_BYTES" >&2
  echo "Move detailed material to ~/.asha/reference/ and keep the hot identity compact." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT")"

if [[ -f "$OUTPUT" ]] && cmp -s "$tmp" "$OUTPUT"; then
  exit 0   # no-op (idempotent)
fi

mv "$tmp" "$OUTPUT"
trap - EXIT
echo "wrote merged identity -> $OUTPUT ($(wc -l < "$OUTPUT") lines, $merged_bytes bytes)"
