#!/usr/bin/env bash
# operational-merge.sh — emit operation.md plus active Memory v2 learnings.
#
# For harnesses that inject context through a *file* rather than a SessionStart
# hook (Copilot, Codex). On Claude the same content rides
# plugins/session/hooks/handlers/session-start.sh; this is the file-based
# equivalent for harnesses without a usable hook.
#
# Output is plain markdown suitable as a Copilot
# `.github/instructions/*.instructions.md` body (or any always-on instructions
# slot). No <system-reminder> wrappers — those are a Claude-hook convention.
#
# Budgets and truncation come from plugins/session/hooks/handlers/
# operational-budget.sh, which session-start.sh also sources, so every harness
# receives the same text. Fallback when operation.md is absent: CORE.md.
#
# Usage: operational-merge.sh <output-path>
# Exit 0 on success; 1 if there is nothing to emit (no operation + no learnings)
# or on a usage error — callers treat exit 1 as "no operational layer".

set -euo pipefail

# asha-bootstrap-symlink-walk: resolve our own real path, portable (readlink -f is GNU-only).
# Duplicated across scripts — find all: `grep -rn asha-bootstrap-symlink-walk`. Cannot DRY into
# lib/portable.sh:resolve_path() — this runs *before* portable.sh is locatable. Keep copies in sync.
__asha_src="${BASH_SOURCE[0]}"
while [ -h "$__asha_src" ]; do
  __asha_dir="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
  __asha_src="$(readlink "$__asha_src")"
  case "$__asha_src" in /*) ;; *) __asha_src="$__asha_dir/$__asha_src" ;; esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
unset __asha_src __asha_dir
ASHA_ROOT="$(dirname "$SCRIPT_DIR")"

OUTPUT="${1:-}"
[[ -n "$OUTPUT" ]] || { echo "usage: $0 <output-path>" >&2; exit 1; }

ASHA_DIR="${ASHA_HOME:-$HOME/.asha}"
OPERATION_FILE="$ASHA_DIR/operation.md"
LEARNINGS_DIR="$ASHA_DIR/learnings"
LEARNINGS_MANAGER="$ASHA_ROOT/plugins/session/tools/learnings_manager.py"
CORE_MD="$ASHA_ROOT/plugins/session/modules/CORE.md"

# shellcheck source=../plugins/session/hooks/handlers/operational-budget.sh
source "$ASHA_ROOT/plugins/session/hooks/handlers/operational-budget.sh"

PYTHON_CMD=""
command -v python3 >/dev/null 2>&1 && PYTHON_CMD="python3"

OPERATION_CONTENT=""
LEARNINGS_CONTENT=""

[[ -f "$OPERATION_FILE" ]] && \
  OPERATION_CONTENT="$(asha_budget_truncate "$(cat "$OPERATION_FILE")" "$ASHA_OPERATION_MAX_BYTES" "operation.md")"

# Candidates and retired records do not acquire authority by existing.
if [[ -d "$LEARNINGS_DIR" && -f "$LEARNINGS_MANAGER" && -n "$PYTHON_CMD" ]]; then
  RENDERED_ACTIVE="$("$PYTHON_CMD" "$LEARNINGS_MANAGER" render-active --max-bytes "$ASHA_LEARNINGS_MAX_BYTES" 2>/dev/null || true)"
  [[ -n "$RENDERED_ACTIVE" ]] && \
    LEARNINGS_CONTENT="$(asha_budget_truncate "$RENDERED_ACTIVE" "$ASHA_LEARNINGS_MAX_BYTES" "active learnings")"
fi

# Fall back to CORE.md if operation.md doesn't exist yet.
[[ -z "$OPERATION_CONTENT" && -f "$CORE_MD" ]] && \
  OPERATION_CONTENT="$(asha_budget_truncate "$(cat "$CORE_MD")" "$ASHA_OPERATION_MAX_BYTES" "CORE.md")"

# Nothing to emit → signal caller (no file written).
[[ -z "$OPERATION_CONTENT" && -z "$LEARNINGS_CONTENT" ]] && exit 1

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Asha Operational Layer (merged)"
  echo ""
  echo "_Generated by \`operational-merge.sh\` from ~/.asha/operation.md + active learnings."
  echo "Edits will be overwritten. On Claude this same content loads via the"
  echo "SessionStart hook._"
  echo ""
  if [[ -n "$OPERATION_CONTENT" ]]; then
    echo "## Operational guidelines"
    echo ""
    printf '%s\n' "$OPERATION_CONTENT"
    echo ""
  fi
  if [[ -n "$LEARNINGS_CONTENT" ]]; then
    echo "## Active learnings"
    echo ""
    printf '%s\n' "$LEARNINGS_CONTENT"
    echo ""
  fi
} > "$tmp"
mv "$tmp" "$OUTPUT"
