#!/usr/bin/env bash
# operational-merge.sh — emit Asha's operational layer (operation.md + learnings
# hot tier) as a single markdown file.
#
# For harnesses that inject context through a *file* rather than a SessionStart
# hook (Copilot, Codex). On Claude the same content rides
# plugins/session/hooks/handlers/session-start.sh; this is the file-based
# equivalent for harnesses without a usable hook.
#
# Output is plain markdown suitable as a Copilot
# `.github/instructions/*.instructions.md` body (or any always-on instructions
# slot). No <system-reminder> wrappers — those are a Claude-hook convention.
#
# Budgets + fallbacks MIRROR session-start.sh's operational layer — KEEP IN SYNC:
#   - operation.md, cap 4000 chars, fallback CORE.md
#   - learnings hot tier via `learnings_manager.py render-hot --max-bytes 3000`,
#     fallback legacy flat ~/.asha/learnings.md
#
# Usage: operational-merge.sh <output-path>
# Exit 0 on success; 1 if there is nothing to emit (no operation + no learnings)
# or on a usage error — callers treat exit 1 as "no operational layer".

set -euo pipefail

# asha-bootstrap-symlink-walk: resolve our own real path, portable (readlink -f is GNU-only).
# Duplicated across scripts — find all: `grep -rn asha-bootstrap-symlink-walk`. Cannot DRY into
# lib/portable.sh:resolve_path() — this runs *before* portable.sh is locatable. Keep copies in sync.
__asha_src="${BASH_SOURCE[0]}"
while [ -h "$__asha_src" ]; do
  __asha_dir="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
  __asha_src="$(readlink "$__asha_src")"
  case "$__asha_src" in /*) ;; *) __asha_src="$__asha_dir/$__asha_src" ;; esac
done
SCRIPT_DIR="$(cd -P "$(dirname "$__asha_src")" >/dev/null 2>&1 && pwd)"
unset __asha_src __asha_dir
ASHA_ROOT="$(dirname "$SCRIPT_DIR")"

OUTPUT="${1:-}"
[[ -n "$OUTPUT" ]] || { echo "usage: $0 <output-path>" >&2; exit 1; }

ASHA_DIR="$HOME/.asha"
OPERATION_FILE="$ASHA_DIR/operation.md"
LEARNINGS_DIR="$ASHA_DIR/learnings"           # OKF concept bundle (current)
LEARNINGS_FILE="$ASHA_DIR/learnings.md"       # legacy flat file (pre-migration fallback)
LEARNINGS_MANAGER="$ASHA_ROOT/plugins/session/tools/learnings_manager.py"
CORE_MD="$ASHA_ROOT/plugins/session/modules/CORE.md"

OPERATION_MAX=4000
LEARNINGS_MAX=3000

PYTHON_CMD=""
command -v python3 >/dev/null 2>&1 && PYTHON_CMD="python3"

truncate_content() {
  local content="$1" max_chars="$2" label="$3"
  local length=${#content}
  if [[ $length -le $max_chars ]]; then
    printf '%s' "$content"
  else
    printf '%s\n\n[Truncated: %s exceeded %s chars (%s total). Read the full file if needed.]' \
      "${content:0:$max_chars}" "$label" "$max_chars" "$length"
  fi
}

OPERATION_CONTENT=""
LEARNINGS_CONTENT=""

[[ -f "$OPERATION_FILE" ]] && \
  OPERATION_CONTENT="$(truncate_content "$(cat "$OPERATION_FILE")" "$OPERATION_MAX" "operation.md")"

# Learnings: render the hot tier from the OKF bundle (confidence-ranked, budgeted).
# Fall back to the legacy flat file for setups not yet migrated to the bundle.
if [[ -d "$LEARNINGS_DIR" && -f "$LEARNINGS_MANAGER" && -n "$PYTHON_CMD" ]]; then
  RENDERED_HOT="$("$PYTHON_CMD" "$LEARNINGS_MANAGER" render-hot --max-bytes "$LEARNINGS_MAX" 2>/dev/null || true)"
  [[ -n "$RENDERED_HOT" ]] && \
    LEARNINGS_CONTENT="$(truncate_content "$RENDERED_HOT" "$LEARNINGS_MAX" "learnings hot tier")"
elif [[ -f "$LEARNINGS_FILE" ]]; then
  LEARNINGS_CONTENT="$(truncate_content "$(cat "$LEARNINGS_FILE")" "$LEARNINGS_MAX" "learnings.md")"
fi

# Fall back to CORE.md if operation.md doesn't exist yet.
[[ -z "$OPERATION_CONTENT" && -f "$CORE_MD" ]] && \
  OPERATION_CONTENT="$(truncate_content "$(cat "$CORE_MD")" "$OPERATION_MAX" "CORE.md")"

# Nothing to emit → signal caller (no file written).
[[ -z "$OPERATION_CONTENT" && -z "$LEARNINGS_CONTENT" ]] && exit 1

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
{
  echo "# Asha Operational Layer (merged)"
  echo ""
  echo "_Generated by \`operational-merge.sh\` from ~/.asha/operation.md + the learnings"
  echo "hot tier. Edits will be overwritten. On Claude this same content loads via the"
  echo "SessionStart hook._"
  echo ""
  if [[ -n "$OPERATION_CONTENT" ]]; then
    echo "## Operational guidelines"
    echo ""
    printf '%s\n' "$OPERATION_CONTENT"
    echo ""
  fi
  if [[ -n "$LEARNINGS_CONTENT" ]]; then
    echo "## Learnings (hot tier)"
    echo ""
    printf '%s\n' "$LEARNINGS_CONTENT"
    echo ""
  fi
} > "$tmp"
mv "$tmp" "$OUTPUT"
